### ISSUE TITLE
Not working for me on mac

### ISSUE THREAD

**Issue by Julix91** [davidmarkclements/screenres#12]
Not working for me on MacOS

I'm thinking it's to do with `/osx.cc:57:5: warning: 'CGConfigureDisplayMode' is deprecated: first
      deprecated in macOS 10.6 - No longer supported [-Wdeprecated-declarations]`

but here's the full log in case.

```
iMac-JulianSloman:browsersync juliansloman$ npm install

> fsevents@1.2.4 install /Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/fsevents
> node install

[fsevents] Success: "/Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-expat@2.3.17 install /Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node

> screenres@2.0.1 install /Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/screenres
> node-gyp rebuild

  CXX(target) Release/obj.target/screenres/linux.o
  CXX(target) Release/obj.target/screenres/osx.o
../osx.cc:45:16: warning: 'CGDisplayBestModeForParameters' is deprecated: first
      deprecated in macOS 10.6 - No longer supported [-Wdeprecated-declarations]
  switchMode = CGDisplayBestModeForParameters(mainDisplay, 32, h, v, NULL);
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:473:38: note: 
      'CGDisplayBestModeForParameters' has been explicitly marked deprecated
      here
CG_EXTERN CFDictionaryRef __nullable CGDisplayBestModeForParameters(
                                     ^
../osx.cc:57:5: warning: 'CGConfigureDisplayMode' is deprecated: first
      deprecated in macOS 10.6 - No longer supported [-Wdeprecated-declarations]
    CGConfigureDisplayMode(config, display, mode);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:408:19: note: 
      'CGConfigureDisplayMode' has been explicitly marked deprecated here
CG_EXTERN CGError CGConfigureDisplayMode(CGDisplayConfigRef __nullable config,
                  ^
2 warnings generated.
  CXX(target) Release/obj.target/screenres/win.o
  CXX(target) Release/obj.target/screenres/screenres.o
  SOLINK_MODULE(target) Release/screenres.node

> jsonpath@1.0.0 postinstall /Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

npm WARN browser_sync_test@1.0.0 No description
npm WARN browser_sync_test@1.0.0 No repository field.

added 453 packages from 342 contributors and audited 2655 packages in 25.243s
found 0 vulnerabilities

iMac-JulianSloman:browsersync juliansloman$ node bs.js
dyld: lazy symbol binding failed: Symbol not found: _CGMainDisplayID
  Referenced from: /Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/screenres/build/Release/screenres.node
  Expected in: flat namespace

dyld: Symbol not found: _CGMainDisplayID
  Referenced from: /Users/juliansloman/Dev/ffs-mainsite/julix/browsersync/node_modules/screenres/build/Release/screenres.node
  Expected in: flat namespace

Abort trap: 6
```

**Comment by patrick-motard** [comment]
```
npm i --save screenres        

> screenres@2.0.1 install /Users/pmotard/Code/trip/node_modules/screenres
> node-gyp rebuild

  CXX(target) Release/obj.target/screenres/linux.o
  CXX(target) Release/obj.target/screenres/osx.o
../osx.cc:45:16: warning: 'CGDisplayBestModeForParameters' is
      deprecated: first deprecated in macOS 10.6 - No longer
      supported [-Wdeprecated-declarations]
  switchMode = CGDisplayBestModeForParameters(mainDispl...
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:473:38: note: 
      'CGDisplayBestModeForParameters' has been explicitly
      marked deprecated here
CG_EXTERN CFDictionaryRef __nullable CGDisplayBestModeF...
                                     ^
../osx.cc:57:5: warning: 'CGConfigureDisplayMode' is
      deprecated: first deprecated in macOS 10.6 - No longer
      supported [-Wdeprecated-declarations]
    CGConfigureDisplayMode(config, display, mode);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:408:19: note: 
      'CGConfigureDisplayMode' has been explicitly marked
      deprecated here
CG_EXTERN CGError CGConfigureDisplayMode(CGDisplayConfi...
                  ^
2 warnings generated.
  CXX(target) Release/obj.target/screenres/win.o
  CXX(target) Release/obj.target/screenres/screenres.o
../screenres.cc:15:11: error: no member named 'Handle' in
      namespace 'v8'
using v8::Handle;
      ~~~~^
../screenres.cc:22:11: error: no template named 'Handle'
void init(Handle<Object>);
          ^
../screenres.cc:26:45: error: too few arguments to function
      call, single argument 'context' was not specified
  int code = changeRes(info[0]->Uint32Value(), info[1]-...
                       ~~~~~~~~~~~~~~~~~~~~ ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8.h:2707:3: note: 
      'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unuse...
                              ^
../screenres.cc:26:69: error: too few arguments to function
      call, single argument 'context' was not specified
  ...info[1]->Uint32Value());
     ~~~~~~~~~~~~~~~~~~~~ ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8.h:2707:3: note: 
      'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unuse...
                              ^
../screenres.cc:39:8: warning: 'Set' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
  arr->Set(0, Nan::New<Number>(res.width));
       ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8.h:3507:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8config.h:328:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../screenres.cc:40:8: warning: 'Set' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
  arr->Set(1, Nan::New<Number>(res.height));
       ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8.h:3507:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8config.h:328:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../screenres.cc:45:107: error: too few arguments to function
      call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(set)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8.h:6126:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unuse...
                              ^
../screenres.cc:46:107: error: too few arguments to function
      call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(get)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8.h:6126:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/pmotard/Library/Caches/node-gyp/12.16.3/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unuse...
                              ^
2 warnings and 6 errors generated.
make: *** [Release/obj.target/screenres/screenres.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pmotard/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/pmotard/.nvm/versions/node/v12.16.3/bin/node" "/Users/pmotard/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pmotard/Code/trip/node_modules/screenres
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! screenres@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the screenres@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pmotard/.npm/_logs/2020-05-10T08_02_14_915Z-debug.log
```
