### ISSUE TITLE
Fails on 4.0.0

### ISSUE THREAD

**Issue by IonicaBizau** [davidmarkclements/screenres#4]
I'm using node 4.0.0:

``` sh
$ node
> require("screenres")
{ set: [Function], get: [Function] }
> require("screenres").get()
node: symbol lookup error: /home/ionicabizau/.../node_modules/screenres/build/Release/screenres.node: undefined symbol: _Z8fetchResv
```

**Comment by IonicaBizau** [comment]
Hmm... @davidmarkclements any response?

**Comment by davidmarkclements** [comment]
@IonicaBizau thanks for the bump I missed this 

This looks possibly related to an api change in NAN or maybe v8

Just to make absolutely sure - you didn't install it with one version of node, then switch and try the above without an `npm rebuild`? 

If not I'll take a look at my next opp

**Comment by IonicaBizau** [comment]
@davidmarkclements Actually, now it fails at the installation step–so it could be related to node-gyp. Maybe I will have something to contribute here. :smile:

**Comment by IonicaBizau** [comment]
@davidmarkclements Additional info after updating the dependencies (#5). When `npm install`ing I get these errors. You probably know better what's going on. I'm not a C++ hacker.

Some relevant logs:

``` log
...
npm http request GET https://registry.npmjs.org/lodash.repeat
npm http 304 https://registry.npmjs.org/lodash.repeat

> screenres@1.0.2 install /home/ionicabizau/Documents/screenres
> node-gyp rebuild

make: Entering directory '/home/ionicabizau/Documents/screenres/build'
  CXX(target) Release/obj.target/screenres/linux.o
../linux.cc: In function ‘Resolution fetchRes()’:
../linux.cc:16:48: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   fgets(screenSize, sizeof(screenSize) - 1, fp);
                                                ^
../linux.cc: In function ‘int changeRes(int, int)’:
../linux.cc:40:40: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   fgets(active, sizeof(active) - 1, fp);
                                        ^
../linux.cc:44:44: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   fgets(modeline, sizeof(modeline) - 1, fp);
                                            ^
../linux.cc:53:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(newmode);
                  ^
../linux.cc:60:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(addmode);
                  ^
../linux.cc:66:17: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(setres);
                 ^
  CXX(target) Release/obj.target/screenres/osx.o
  CXX(target) Release/obj.target/screenres/screenres.o
In file included from ../screenres.cc:9:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../screenres.cc:9:
/home/ionicabizau/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ionicabizau/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../screenres.cc:9:0:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../screenres.cc:9:
/home/ionicabizau/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ionicabizau/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../screenres.cc:9:0:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
screenres.target.mk:92: recipe for target 'Release/obj.target/screenres/screenres.o' failed
make: *** [Release/obj.target/screenres/screenres.o] Error 1
make: Leaving directory '/home/ionicabizau/Documents/screenres/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ionicabizau/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-10-generic
gyp ERR! command "/home/ionicabizau/.nvm/versions/node/v4.0.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ionicabizau/Documents/screenres
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

npm ERR! Linux 4.2.0-10-generic
npm ERR! argv "/home/ionicabizau/.nvm/versions/node/v4.0.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v4.0.0/bin/npm" "i"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! screenres@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the screenres@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the screenres package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls screenres
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionicabizau/Documents/screenres/np

m-debug.log
```

**Comment by IonicaBizau** [comment]
@davidmarkclements I hacked the C++ file, porting it to latest Nan version.
Big thanks to @ErikDubbelboer's [related commit in `node-sleep`](https://github.com/ErikDubbelboer/node-sleep/commit/bebfd6c19cb8c7055d29682446df99088c54bc06?diff=split). :tada: :joy: :fireworks: 

[![](http://33.media.tumblr.com/1d43607cce1b88320c52c9d4ece041ae/tumblr_msvbdvnTOu1sewz1yo1_400.gif)](http://nodejsreactions.tumblr.com/post/64214355721/node-programmer-having-to-fix-a-bug-in-native)

**Comment by davidmarkclements** [comment]
awesome - opening a separate issue for os x support
